Radek
MOCOS-COVID19/MocosSimLauncher pull request #5
Opened 2021-08-20 07:07 UTC by ridzikowski

add travels and stop conditions to launcher

2021-08-21 21:29 UTC, tozanski requested changes
It would be the best to split the PR into two parts, each coresponding to one of the changes:
they are two separate contibutions and because I believe the time limit part can be merged sooner as we do not need to wait for changes in MocosSim

2021-08-21 21:29 UTC, tozanski commented on src/MocosSimLauncher.jl
> +  end
something like this should work
`time_limit = get(json, "stop_simulation_time", typemax(MocosSim.TimePoint)) |> MocosSim.TimePoint`

2021-08-21 21:29 UTC, tozanski commented on src/callback.jl
> +DetectionCallback(sz::Integer, max_num_infected::Integer=10^8, time_limit::MocosSim.TimePoint=365) = DetectionCallback(
I believe `typemax(MocosSim.TimePoint)` is less breaking change default

2021-08-21 21:29 UTC, tozanski commented on example/myexample.json
> +}
The name of the file can be easilty confused with the file that is already there `example.json`. That one is also used for precompilation so all the we should have all the features enabled there

2021-08-25 11:53 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +  end
ok, it's working

2021-08-25 11:53 UTC, ridzikowski commented on src/callback.jl
> +DetectionCallback(sz::Integer, max_num_infected::Integer=10^8, time_limit::MocosSim.TimePoint=365) = DetectionCallback(
ok

2021-08-25 11:57 UTC, ridzikowski commented on example/myexample.json
> +}
i use different files for simple testing. I will be careful to  commit only  `example.json`

2021-09-02 03:51 UTC, eMaerthin commented on example/example.json
> +    "frequency" : 0.05
please update this

2021-09-02 12:48 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +  @info "stop_simulation" time_limit
ok

2021-09-02 12:54 UTC, ridzikowski commented on example/example.json
> +    "friendship": 0.0
something was working wrong, so I asked Marcin for his values/factors, but problem was in my code

2021-09-02 12:56 UTC, ridzikowski commented on example/example.json
> +    "household": 0.0217,
ok

2021-09-02 13:36 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +        import_fun = MocosSim.make_imported_cases(import_name; import_params...)
i split and move this.

2021-09-02 16:59 UTC, tozanski commented on src/MocosSimLauncher.jl
> +    for imp in import_funcs
```suggestion
    for (name, params) in import_funcs
```

2021-09-02 16:59 UTC, tozanski commented on example/example.json
> +    "usage" : 0.03,
👍

2021-09-02 16:59 UTC, tozanski commented on example/example.json
> +    "household": 0.01,
👍

2021-09-02 17:04 UTC, tozanski commented on src/MocosSimLauncher.jl
> +  import_funcs = Array{Tuple{String,Dict{String,Any}},1}(undef,0)
```suggestion
  import_funcs = MocosSim.AbstractImportedCases[]
```

2021-09-02 17:07 UTC, tozanski commented on src/MocosSimLauncher.jl
>    initial_conditions = json["initial_conditions"]
for compatibility please add the new initializer if this is present

2021-09-05 14:45 UTC, eMaerthin commented
@tozanski @ridzikowski can we merge it?

2021-09-05 15:47 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +  import_funcs = Array{Tuple{String,Dict{String,Any}},1}(undef,0)
fix

2021-09-05 15:50 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +    for imp in import_funcs
when i converted the list this case resolved

2021-09-05 15:50 UTC, ridzikowski commented on example/example.json
> +    "frequency" : 0.05
ok

2021-09-05 15:57 UTC, ridzikowski commented on src/MocosSimLauncher.jl
>    initial_conditions = json["initial_conditions"]
do you have suggestions on where to place it?

2021-09-17 09:56 UTC, tozanski reviewed
Please limit the changes in example.json

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> +  "stop_simulation_time" : 20
100 days should be OK, so that the simulation runs for enough time

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> +      "infectious": 50
```suggestion
      "infectious": 100
```

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> -  },
please restore

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> +    "constant": 1.8225,
the old value was fine, especially if we have the strain settable now

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> +    "testing_time" : 3.0
```suggestion
    "testing_time" : 0.25
```

2021-09-17 09:56 UTC, tozanski commented on example/example.json
> +  "detection_mild_proba" : 0.3,
👍

2021-09-17 09:58 UTC, tozanski commented on LICENSE
> +Copyright (c) 2020, MOCOS Research Group at WrUST (TBU)
👍 you can also add yourself as an author of the package

2021-09-17 09:59 UTC, tozanski commented on example/example.json
> +    "friendship": 0.0
can be removed

2021-09-17 10:13 UTC, ridzikowski commented on example/example.json
> +  "stop_simulation_time" : 20
yes, the short time was just for my tests

2021-09-17 10:16 UTC, ridzikowski commented on example/example.json
> +    "friendship": 0.0
oki

2021-09-17 10:17 UTC, ridzikowski commented on example/example.json
> -  },
ok

2021-09-17 10:23 UTC, ridzikowski commented on example/example.json
> +    "constant": 1.8225,
ok, i restored old values

2021-09-17 10:25 UTC, tozanski commented on example/example.json
> -  "modulation":{
I've missed that the modulation is gone too, should be restored so it is tested on CI

2021-09-17 10:26 UTC, tozanski commented on example/example.json
> +  "num_trajectories" : 5,
```suggestion
  "num_trajectories" : 10,
```

2021-09-17 10:31 UTC, ridzikowski commented on example/example.json
> -  "modulation":{
ok, i restored it too

2021-09-17 11:17 UTC, tozanski reviewed
Few more comments to the StrainKind parsing

2021-09-17 11:17 UTC, tozanski commented on src/MocosSimLauncher.jl
> +  import_funcs = MocosSim.AbstractOutsideCases[]
no need to create this list if it is used only once

2021-09-17 11:17 UTC, tozanski commented on src/MocosSimLauncher.jl
> +      if haskey(fun["params"],"strain")
this will crash if there is no `fun["params"]` defined. The default is handled nicely in the line above

2021-09-17 11:17 UTC, tozanski commented on src/MocosSimLauncher.jl
> +        import_preparams["strain"] = eval(Meta.parse("MocosSim.$strain"))
we should avoid calling `eval`. The easiest way (and probably safe) to get enum instance should be to call `getfield(MocosSim, Symbol(string))::MocosSim.StrainKind`

2021-09-17 11:18 UTC, tozanski commented on src/MocosSimLauncher.jl
> +  import_funcs = MocosSim.AbstractOutsideCases[]
the import functions can be executed immediately

2021-09-17 11:19 UTC, tozanski commented on src/MocosSimLauncher.jl
> +  import_funcs = MocosSim.AbstractOutsideCases[]
No, you are right we need to save them for multiple trajectories

2021-09-17 11:52 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +        import_preparams["strain"] = eval(Meta.parse("MocosSim.$strain"))
ok, corrected, I will remember for the future

2021-09-17 11:53 UTC, ridzikowski commented on src/MocosSimLauncher.jl
> +      if haskey(fun["params"],"strain")
good point, was corrected

2021-09-17 13:03 UTC, tozanski approved these changes
LGTM

2021-09-17 13:04 UTC, merged